In [1]:
import pandas as pd
import ast

import warnings
warnings.filterwarnings("ignore")

In [2]:
#Cargamos JSON
archivo = 'australian_users_items.json'

# Lo leemos línea a línea
fs = []
with open(archivo, encoding = 'utf-8') as file:
    for line in file.readlines():
        fs.append(ast.literal_eval(line))

# Armamos el dataframe
df_1 = pd.DataFrame(fs)
df_1

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."
...,...,...,...,...,...
88305,76561198323066619,22,76561198323066619,http://steamcommunity.com/profiles/76561198323...,"[{'item_id': '413850', 'item_name': 'CS:GO Pla..."
88306,76561198326700687,177,76561198326700687,http://steamcommunity.com/profiles/76561198326...,"[{'item_id': '11020', 'item_name': 'TrackMania..."
88307,XxLaughingJackClown77xX,0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,[]
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"[{'item_id': '304930', 'item_name': 'Unturned'..."
88309,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,[]

In [3]:
# Eliminamos las filas con todos los registros nulos (si las hubiere)
df_2 = df_1.dropna(how='all').reset_index(drop=True)
df_2.shape

(88310, 5)

In [4]:
# Elimino duplicados
df_2 = df_2.drop_duplicates(subset="user_id")

In [5]:
df_2.shape

(87626, 5)

In [6]:
# Elimino las filas donde items_count = 0
df_2 = df_2.drop(df_2[df_2["items_count"] == 0].index)
df_2.reset_index(drop=True, inplace=True)

In [7]:
df_2

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."
...,...,...,...,...,...
70907,76561198320136420,321,76561198320136420,http://steamcommunity.com/profiles/76561198320...,"[{'item_id': '11020', 'item_name': 'TrackMania..."
70908,ArkPlays7,4,76561198321542621,http://steamcommunity.com/id/ArkPlays7,"[{'item_id': '218230', 'item_name': 'PlanetSid..."
70909,76561198323066619,22,76561198323066619,http://steamcommunity.com/profiles/76561198323...,"[{'item_id': '413850', 'item_name': 'CS:GO Pla..."
70910,76561198326700687,177,76561198326700687,http://steamcommunity.com/profiles/76561198326...,"[{'item_id': '11020', 'item_name': 'TrackMania..."
70911,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"[{'item_id': '304930', 'item_name': 'Unturned'..."

In [8]:
# Como vimos en el shape no había registros nulos. Ahora procedemos a desanidar y quedarnos únicamente con las columnas que nos serán de utilidad más adelante. 
item_e = []
for i, row in df_2.iterrows():
    user_id = row['user_id']
    
    for j in row['items']:
        item_1= {
                'user_id': user_id,        
                'item_id': j['item_id'],
                'item_name': j['item_name'],
                'playtime_forever': j['playtime_forever']
                }
        item_e.append(item_1) # Agremos a desanidado el diccionario item_new
df_3= pd.DataFrame(item_e)

In [9]:
df_3

,user_id,item_id,item_name,playtime_forever
0,76561197970982479,10,Counter-Strike,6
1,76561197970982479,20,Team Fortress Classic,0
2,76561197970982479,30,Day of Defeat,7
3,76561197970982479,40,Deathmatch Classic,0
4,76561197970982479,50,Half-Life: Opposing Force,0
...,...,...,...,...
5094077,76561198329548331,346330,BrainBread 2,0
5094078,76561198329548331,373330,All Is Dust,0
5094079,76561198329548331,388490,One Way To Die: Steam Edition,3
5094080,76561198329548331,521570,You Have 10 Seconds 2,4
5094081,76561198329548331,519140,Minds Eyes,3

In [10]:
df_3.drop(df_3[df_3["playtime_forever"] == 0].index, inplace=True)

In [11]:
df_3

,user_id,item_id,item_name,playtime_forever
0,76561197970982479,10,Counter-Strike,6
2,76561197970982479,30,Day of Defeat,7
8,76561197970982479,300,Day of Defeat: Source,4733
9,76561197970982479,240,Counter-Strike: Source,1853
10,76561197970982479,3830,Psychonauts,333
...,...,...,...,...
5094075,76561198329548331,304930,Unturned,677
5094076,76561198329548331,227940,Heroes & Generals,43
5094079,76561198329548331,388490,One Way To Die: Steam Edition,3
5094080,76561198329548331,521570,You Have 10 Seconds 2,4
5094081,76561198329548331,519140,Minds Eyes,3

In [12]:
df_3.dtypes

user_id             object
item_id             object
item_name           object
playtime_forever     int64
dtype: object

In [13]:
# Convertimos los registros de la columna 'item_id' a enteros de 64 bit
df_3['item_id'] = df_3['item_id'].astype('int64')
# Convertimos los registros de la columna 'user_id' a string
df_3['user_id'] = df_3['user_id'].astype(str)

In [18]:
# Lo guardo en csv 
archivo = 'user_items_limpio.csv'
df_3.to_csv(archivo, index=False)
# Lo guardo en parquet para ser utilizado en la api
df_3.to_parquet('user_items_limpio.parquet', compression='gzip')

In [15]:
# Verificamos la grabación del CSV
dfprueba = pd.read_csv('user_items_limpio.csv')
dfprueba

,user_id,item_id,item_name,playtime_forever
0,76561197970982479,10,Counter-Strike,6
1,76561197970982479,30,Day of Defeat,7
2,76561197970982479,300,Day of Defeat: Source,4733
3,76561197970982479,240,Counter-Strike: Source,1853
4,76561197970982479,3830,Psychonauts,333
...,...,...,...,...
3246347,76561198329548331,304930,Unturned,677
3246348,76561198329548331,227940,Heroes & Generals,43
3246349,76561198329548331,388490,One Way To Die: Steam Edition,3
3246350,76561198329548331,521570,You Have 10 Seconds 2,4
3246351,76561198329548331,519140,Minds Eyes,3